name: Update HiScores
on:
  workflow_dispatch:
  schedule:
    - cron: '40 */2 * * *'
 
jobs:
  hiscores:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Generate new hiscores
        run: |
          pip3 install requests
          python3 ./scripts/updateHiscores.py
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update hiscores.csv'
          file_pattern: 'data/hiscores.csv'
          skip_fetch: false
          skip_checkout: false
