name: Update Hiscores
on:
  workflow_dispatch:
  schedule:
    - cron: '6 */6 * * *'
 
jobs:
  hiscores:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Generate new hiscores
        run: python3 ./scripts/updateHiscores.py
      - name: Commit files
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            data/hiscores.csv
            data/usernames.csv
          commit-msg: Update hiscores.csv and usernames.csv
          github-token: ${{ secrets.GITHUB_TOKEN }}
